#!/bin/bash

cat <<EOF >> /alarm/buildout.cfg
[buildout]
index = http://pypi.doubanio.com/simple
find-links = 
EOF

mkdir -p ~/.pip
cat <<EOF >> ~/.pip/pip.conf
[global]
index-url = http://pypi.doubanio.com/simple
[install]
trusted-host = pypi.doubanio.com
EOF

cat <<EOF > ~/.pydistutils.cfg
[easy_install]
index-url=http://pypi.doubanio.com/simple
EOF
